### PR TITLE
Add new method decodeBridgeTransaction

### PR DESCRIPTION
**Pull request by nathanieliov**

### CODE REVIEW

**Comment by kelvinator07** [comment]
Can You Update The ReadME To Reflect How To Use The New Tool?

**Comment by nathanieliov** [comment]
> Can You Update The ReadME To Reflect How To Use The New Tool?

Sure, I can.

**Comment by nathanieliov** [comment]
@kelvinator07  done

**Review by jeremy-then — APPROVED** [review]
LGTM.

**Pull request merged**
